spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/marketplace_dev
    username: dev
    password: dev123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  logging:
    level:
        com.marketplace.backend: DEBUG
        org.hibernate.SQL: DEBUG
        org.flywaydb: DEBUG